apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark # Make sure this matches the namespace you use for Spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spark # Make sure this matches the namespace you use for Spark
rules:
  # Permissions for the Spark Driver to manage its own pods and executors
  - apiGroups: [""] # "" indicates core API group (pods, services, configmaps)
    resources: ["pods", "pods/log", "services", "configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"] # patch is important for some Spark versions/features
  # Permissions for Spark to get Node information (useful for scheduling)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # If you use Spark volumes or custom resources, you might need more.
  # For a simple test, the above should be sufficient.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spark # Make sure this matches the namespace you use for Spark
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark # Make sure this matches the namespace you use for Spark
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io